### ISSUE TITLE
网易云插件存在可能无法播放音乐和导致语音识别启动时间过短的情况

### ISSUE THREAD

**Issue by GoldJohnKing** [dingdang-robot/dingdang-contrib#27]
叮当在播放音乐时偶尔会出现读了歌曲名但实际上没有播放的情况，log如下：

> INFO:client.stt:PocketSphinx 识别到了：['HEYDINGDANG']
> INFO:client.stt:阿里云语音识别到了: 播放音乐
> ERROR:MusicBoxApi.api:[Errno 2] No such file or directory: u'/root/.netease-musicbox/cookie'
> DEBUG:MusicBoxApi.api:{"phone": "15541769173", "password": "f1afe316cd4fadaad3bbc3969bd1934e", > "rememberLogin": "true"}
> /bin/sh: 1: task: not found
> ERROR:client.app_utils:invalid literal for int() with base 10: ''
> DEBUG:MusicBoxApi.api:{"csrf_token": "6fc30568fe26c085791285b9c093befd", "ids": [506092035], "br": 320000}
> [DEBUG] sync_check: -1 -1

另外，一旦log中出现`[DEBUG] sync_check: -1 -1`，依然有语音识别过晚开始和过早结束，无法把握说话时机的情况。而且据观察，在音乐播放以外的地方并没有出现过该提示。

**Comment by wzpan** [comment]
@GoldJohnKing 已找出原因，是由于你的歌单里头有版权问题无法播放或者已下架的的歌曲，这首歌曲返回的音乐地址是错误的，导致播放失败。将这些歌曲从你的歌单里剔除，然后清掉 `~/.netease_music` 目录以及 `~/userInfo` 再试试。

**Comment by wzpan** [comment]
又验证了一下，看来是网易云音乐的api变了，现在已经拿不到正确的地址了。

**Comment by SkyAzure** [comment]
`musicbox`2017-11-28 版本 0.2.4.2 更新获取歌曲列表的 api
[https://github.com/darknessomi/musicbox](url)
@wzpan

**Comment by wzpan** [comment]
收到，我更新下。

**Comment by wzpan** [comment]
已修复
