### ISSUE TITLE
在profile.yml写入 关机的插件，还有就是修改叮当开机的用户模式

### ISSUE THREAD

**Issue by Patrick-Liu1** [dingdang-robot/dingdang-contrib#47]
# 关机
halt：

我不知道，配置项在写什么，在Halt.py的文件里没有Slug标识符。我对着麦说关机，提示配置有问题，使用插件失败
=====================================================================
修改叮当的开机自启动，我看的是http://bbs.hahack.com/t/topic/43/1这个网上的教程，到创建软连接的时候，出现，.dingdang文件以存在的问题。

**Comment by wzpan** [comment]
已修复，无需配置即可使用。
