### ISSUE TITLE
叮当接入hass

### ISSUE THREAD

**Issue by Jesse54211** [dingdang-robot/dingdang-contrib#68]
叮当语音和homeassistant连接控制开关灯的视频。我想请教你一下，叮当的官方文档说的在叮当配置文件里添加ip和端口和密码，这里不用填用户名的话不能登录hass呀，那还是填mqtt服务器的ip啊？hass的customeize.yaml文件也弄好了也include进去了，就是叮当配置那里搞不定了

**Comment by wzpan** [comment]
hass 是 @Deschanel 贡献的插件，建议咨询他。见：https://github.com/wzpan/dingdang-robot/pull/42

**Comment by Jesse54211** [comment]
@

**Comment by Jesse54211** [comment]
懂了懂了 是我对hass不了解 他还提供了api的 谢谢啦
